version: "3"
services:
  node-app:
    build: .
    ports:
      "8080:8080"
    env_file:
      - ./.env
  mongo:
    image: mongo
    environment:
      -  MONGO_INITDB_ROOT_USERNAME=admin
      -  MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      -  mongo-db:/data/db

volumes:
  mongo-db: