version: "3"
services:
  node-app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: