version: "3"
services:
  node-app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      -  MONGO_INITDB_ROOT_USERNAME=user
      -  MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      -  mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db: