version: "3"
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - USER=user
      - PASSWORD=password
      - SESSION_SECRET=SESSION_SECRET
    command: npm run dev